# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

# This file is automatically generated by CrossSync. Do not edit manually.

from __future__ import annotations
import time
from functools import wraps
from google.cloud.bigtable.data._metrics.data_model import (
    OPERATION_INTERCEPTOR_METADATA_KEY,
)
from google.cloud.bigtable.data._metrics.data_model import ActiveOperationMetric
from google.cloud.bigtable.data._metrics.data_model import OperationState
from google.cloud.bigtable.data._metrics.handlers._base import MetricsHandler
from grpc import UnaryUnaryClientInterceptor
from grpc import UnaryStreamClientInterceptor


def _with_operation_from_metadata(func):
    """Decorator for interceptor methods to extract the active operation
    from metadata and pass it to the decorated function."""

    @wraps(func)
    def wrapper(self, continuation, client_call_details, request):
        found_operation_id: str | None = None
        try:
            new_metadata: list[tuple[str, str]] = []
            if client_call_details.metadata:
                for k, v in client_call_details.metadata:
                    if k == OPERATION_INTERCEPTOR_METADATA_KEY:
                        found_operation_id = v
                    else:
                        new_metadata.append((k, v))
            client_call_details.metadata = new_metadata
        except Exception:
            pass
        operation: "ActiveOperationMetric" = self.operation_map.get(found_operation_id)
        if operation:
            if (
                operation.state == OperationState.CREATED
                or operation.state == OperationState.BETWEEN_ATTEMPTS
            ):
                operation.start_attempt()
            return func(self, operation, continuation, client_call_details, request)
        else:
            return continuation(client_call_details, request)

    return wrapper


def _end_attempt(operation, exc, metadata):
    """Helper to add metadata and exception to an operation"""
    if metadata is not None:
        operation.add_response_metadata(metadata)
    if exc is not None:
        operation.end_attempt_with_status(exc)


def _get_metadata(source):
    """Helper to extract metadata from a call or RpcError"""
    try:
        return (source.trailing_metadata() or []) + (source.initial_metadata() or [])
    except Exception:
        return None


class BigtableMetricsInterceptor(
    UnaryUnaryClientInterceptor, UnaryStreamClientInterceptor, MetricsHandler
):
    """
    An async gRPC interceptor to add client metadata and print server metadata.
    """

    def __init__(self):
        super().__init__()
        self.operation_map = {}

    def register_operation(self, operation):
        """Register an operation object to be tracked my the interceptor

        When registered, the operation will receive metadata updates:
        - start_attempt if attempt not started when rpc is being sent
        - add_response_metadata after call is complete
        - end_attempt_with_status if attempt receives an error

        The interceptor will register itself as a handeler for the operation,
        so it can unregister the operation when it is complete"""
        self.operation_map[operation.uuid] = operation
        operation.handlers.append(self)

    def on_operation_complete(self, op):
        if op.uuid in self.operation_map:
            del self.operation_map[op.uuid]

    def on_operation_cancelled(self, op):
        self.on_operation_complete(op)

    @_with_operation_from_metadata
    def intercept_unary_unary(
        self, operation, continuation, client_call_details, request
    ):
        encountered_exc: Exception | None = None
        metadata = None
        try:
            call = continuation(client_call_details, request)
            metadata = _get_metadata(call)
            return call
        except Exception as rpc_error:
            metadata = _get_metadata(rpc_error)
            encountered_exc = rpc_error
            raise rpc_error
        finally:
            _end_attempt(operation, encountered_exc, metadata)

    @_with_operation_from_metadata
    def intercept_unary_stream(
        self, operation, continuation, client_call_details, request
    ):
        def response_wrapper(call):
            has_first_response = operation.first_response_latency is not None
            encountered_exc = None
            try:
                for response in call:
                    if not has_first_response:
                        operation.first_response_latency_ns = (
                            time.monotonic_ns() - operation.start_time_ns
                        )
                        has_first_response = True
                    yield response
            except Exception as e:
                encountered_exc = e
                raise
            finally:
                if call is not None:
                    _end_attempt(operation, encountered_exc, _get_metadata(call))

        try:
            return response_wrapper(continuation(client_call_details, request))
        except Exception as rpc_error:
            _end_attempt(operation, rpc_error, _get_metadata(rpc_error))
            raise rpc_error
