# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from google.cloud.bigtable._sync_autogen import _ReadRowsOperation_SyncAutoGenerated
# TODO: use underscore for these
from google.cloud.bigtable._sync_autogen import Table_SyncAutoGenerated
from google.cloud.bigtable._sync_autogen import BigtableDataClient_SyncAutoGenerated


class _ReadRowsOperation_Sync(_ReadRowsOperation_SyncAutoGenerated):

    @staticmethod
    async def _prepare_stream(gapic_stream, *args, **kwargs):
        return gapic_stream

class Table_Sync(Table_SyncAutoGenerated):
    pass

class BigtableDataClient_Sync(BigtableDataClient_SyncAutoGenerated):

    def __init__transport__(self, *args, **kwargs):
        # use grpc transport for sync client
        return "grpc"

    def close(self, timeout: float = 2.0):
        # TODO: Can this be auto-generated?
        self.transport.close()
        self._channel_refresh_tasks = []

    def _ping_and_warm_instances(
        self, channel: grpc.aio.Channel
    ) -> list[GoogleAPICallError | None]:
        ping_rpc = channel.unary_unary(
            "/google.bigtable.v2.Bigtable/PingAndWarmChannel"
        )
        for instance in self._instance_admin_client.list_instances():
            try:
                ping_rpc(instance.name)
            except GoogleAPICallError as exc:
                # fail warm attempts silently
                pass

    def _register_instance(
        self, instance_id: str, owner: Table_SyncAutoGenerated
    ) -> None:
        instance_name = self._gapic_client.instance_path(self.project, instance_id)
        self._instance_owners.setdefault(instance_name, set()).add(id(owner))
        if instance_name not in self._active_instances:
            self._active_instances.add(instance_name)
            # warm all channels for new instance
            for channel in self.transport.channels:
                self._ping_and_warm_instances(channel)


